import os

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
QDRANT_URL = os.getenv("QDRANT_URL", "https://88ea716d-7f10-40d0-88f1-dec59870fe10.us-west-1-0.aws.cloud.qdrant.io:6333")
PDF_PATH = "data/sample.pdf"

LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
LANGCHAIN_PROJECT=os.getenv("LANGCHAIN_PROJECT")
LANGCHAIN_TRACING_V2 =os.getenv("LANGCHAIN_TRACING_V2")
LANGSMITH_TRACING =os.getenv("LANGCHAINSMITH_TRACING")
LANGSMITH_ENDPOINT=os.getenv("LANGSMITH_ENDPOINT")
LANGSMITH_API_KEY=os.getenv("LANGSMITH_API_KEY")
LANGSMITH_PROJECT=os.getenv("LANGSMITH_PROJECT")
